// ============================================================================
//  The /about page. Loaded only when /about is opened.
// ============================================================================

PAGE('about', {
  name: 'Nijin Muhammed',
  portrait: '/images/about-portrait.jpg',
  location: 'Kerala, India',
  bio: `Mentored <strong>500+ design students</strong> and worked with <strong>30+ clients</strong>, delivering user-focused solutions that align experience with business goals. Now expanding into marketing to better connect product, users, and growth.`,
  photo: {
    src: '/images/about-wide.jpg',
    caption: 'Speaking at the graduation ceremony for one of the design batches I mentor at HACA.',
  },
  // The toolkit, rendered as a row of pills on the About page. `icon` names a
  // file in /images/tools/ — the real product mark, not a redrawn one. A plain
  // string still works and renders as a pill with no icon.
  tools: [
    { name: 'Figma', icon: 'figma' },
    { name: 'Framer', icon: 'framer' },
    { name: 'Glide', icon: 'glide' },
    { name: 'Photoshop', icon: 'photoshop' },
    { name: 'Canva', icon: 'canva' },
    { name: 'Linearity', icon: 'linearity' },
    { name: 'Rive', icon: 'rive' },
    { name: 'Icon Composer', icon: 'icon-composer' },
    { name: 'CapCut', icon: 'capcut' },
    { name: 'DaVinci Resolve', icon: 'resolve' },
    { name: 'Shopify', icon: 'shopify' },
    { name: 'Notion', icon: 'notion' },
    { name: 'Zoho', icon: 'zoho' },
    { name: 'Google Docs', icon: 'google-docs' },
    { name: 'Google Sheets', icon: 'google-sheets' },
    { name: 'Linear', icon: 'linear' },
    { name: 'Claude', icon: 'claude' },
    { name: 'ChatGPT', icon: 'chatgpt' },
    { name: 'Cursor', icon: 'cursor' },
    { name: 'Antigravity', icon: 'antigravity' },
    { name: 'VS Code', icon: 'vscode' },
    { name: 'GitHub', icon: 'github' },
    { name: 'Git', icon: 'git' },
    { name: 'React', icon: 'react' },
    { name: 'Tailwind CSS', icon: 'tailwind' },
    { name: 'TypeScript', icon: 'typescript' },
    { name: 'Swift', icon: 'swift' },
    { name: 'Python', icon: 'python' },
    { name: 'Node.js', icon: 'nodejs' },
    { name: 'Firebase', icon: 'firebase' },
    { name: 'Sanity', icon: 'sanity' },
    { name: 'Resend', icon: 'resend' },
    { name: 'Vercel', icon: 'vercel' },
    { name: 'Netlify', icon: 'netlify' },
    { name: 'Cloudflare', icon: 'cloudflare' },
    { name: 'App Store', icon: 'app-store' },
    { name: 'Play Store', icon: 'play-store' },
    { name: 'Google Ads', icon: 'google-ads' },
    { name: 'Meta Ads', icon: 'meta-ads' },
    { name: 'Microsoft Clarity', icon: 'clarity' },
  ],
  skills: [
    'Product Design',
    'E-Commerce',
    'Digital Marketing',
    'No Code Tools',
    'Basic Coding and AI',
    'Graphic Design',
    'Motion Graphics',
    'Video Editing',
  ],
  experience: [
    {
      title: 'UI/UX Design Mentor',
      org: 'HACA (Haris&Co Academy)',
      note: 'Mentoring 500+ design students in fundamentals and real-world product thinking.',
      meta: 'Oct 2025 – Present',
    },
    {
      title: 'Product Designer',
      org: 'Keviz R&D Studio',
      note: 'End-to-end product design across client engagements, from discovery and stakeholder interviews through to annotated engineering handoff.',
      meta: 'Nov 2024 – Oct 2025',
    },
    {
      title: 'UI/UX Designer',
      org: 'Qmark Technolabs',
      note: 'Responsive web and mobile application interfaces for client products, designed inside existing engineering constraints and delivery timelines.',
      meta: 'Apr 2024 – Oct 2024',
    },
    {
      title: 'Designer',
      org: 'TinkerHub Foundation',
      note: "Digital products and campaign systems for one of Kerala's largest student technology communities.",
      meta: 'Oct 2023 – Jun 2024',
    },
    {
      title: 'UI/UX Designer',
      org: 'RITS (Real Information Technology Solutions)',
      note: 'Web application interfaces end to end: requirements gathering, user flows, wireframes, UI and developer handoff. My first design role, alongside the final year of the degree.',
      meta: 'Sep 2023 – Apr 2024',
    },
    {
      title: 'Design Lead',
      org: 'TEDxFarookCollege',
      note: 'Led the design team for a licensed TEDx event: brand system, stage graphics, digital campaigns and web presence.',
      meta: 'Sep 2022 – Apr 2024',
    },
  ],
  education: [
    {
      title: 'BSc Computer Science',
      org: 'Farook College (Autonomous), University of Calicut',
      meta: 'Sep 2021 – Mar 2024',
    },
  ],
});
