// ============================================================================
//  Graphic design — posters and print work. Loaded only when /graphics opens.
//
//  A poster needs `src` to render: the grid drops any entry without artwork,
//  so the rows below are a catalogue waiting for their images. Drop a file in
//  /images/posters and point `src` at it to bring one back.
//
//  `category` groups the grid.
// ============================================================================

PAGE('graphics', [
  { title: 'Fix Your Boring Yards', client: 'Cadillac Landscapers', year: '', category: 'Brand & Agency', src: '' },
  { title: 'The Before & After You Won\'t Believe', client: 'Cadillac Landscapers', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Upgrade Your Outdoor Space', client: 'Cadillac Landscapers', year: '', category: 'Brand & Agency', src: '' },
  { title: 'A Landscape Retreat', client: 'Cadillac Landscapers', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Eid Mubarak', client: 'Confident Corporate Services', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Eid Mubarak — Skyline', client: 'Confident Corporate Services', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Ready to Rule the Digital World', client: 'Moonley Interactive', year: '', category: 'Brand & Agency', src: '' },
  { title: 'We Craft Powerful Brand Stories', client: 'Moonley Interactive', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Landscape Design', client: 'Nature\'s Cradle', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Escape, Heal & Renew', client: 'Panchaganga Ayurveda', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Hair Care', client: 'Panchaganga Ayurveda', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Digital Marketing for Your Business', client: 'Moonley Interactive', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Social Media', client: 'Moonley Interactive', year: '', category: 'Brand & Agency', src: '' },
  { title: '60 Days UAE Visa Change', client: 'Confident Corporate Services', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Social Media Marketing Packages', client: 'Moonley Interactive', year: '', category: 'Brand & Agency', src: '' },
  { title: 'UAE Visit Visa — Lowest Price', client: 'Confident Corporate Services', year: '', category: 'Brand & Agency', src: '' },
  { title: 'International Day of Families', client: 'Confident Corporate Services', year: '', category: 'Brand & Agency', src: '' },
  { title: '10% Coupon — Mon, Tue, Wed', client: 'Leymoon', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Chicken Wrap Deal', client: 'Leymoon', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Tuesday Treat', client: 'Leymoon', year: '', category: 'Brand & Agency', src: '' },
  { title: '$5 Off Special Offer', client: 'Leymoon', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Craving Dubai Adventures?', client: 'Confident Corporate Services', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Bite & Delight', client: 'Koyi Broast', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Tuesday Treat — Any Plate + Drink', client: 'Leymoon', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Eid Holidays Visa Alert', client: 'Confident Corporate Services', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Important Update for Travel Partners', client: 'Confident Corporate Services', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Renew Before the Eid Holidays', client: 'Confident Corporate Services', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Honest Chicken', client: 'Leymoon', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Perfect Family Gatherings', client: 'Leymoon', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Upgrade Your Outdoor Space — Studio', client: 'Cadillac Landscapers', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Fix Your Boring Yards — Garden', client: 'Cadillac Landscapers', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Before & After — Design Studio', client: 'Cadillac Landscapers', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Fix Your Boring Yards — Planters', client: 'Cadillac Landscapers', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Fix Your Boring Yards — Pruning', client: 'Cadillac Landscapers', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Luxe Lounging', client: 'HyDesign Furniture & Interiors', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Modern Minimalism', client: 'HyDesign Furniture & Interiors', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Marble Muse', client: 'HyDesign Furniture & Interiors', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Ethereal Escape', client: 'HyDesign Furniture & Interiors', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Experience the Beauty of Dubai', client: 'Confident Corporate Services', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Exclusive Chair Collection', client: 'HyDesign Furniture & Interiors', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Happy Mother\'s Day', client: 'Leymoon', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Join Our Team — Graphic Designer', client: 'Moonley Interactive', year: '', category: 'Brand & Agency', src: '' },
  { title: 'World Music Day', client: 'Moonley Interactive', year: '', category: 'Brand & Agency', src: '' },
  { title: 'We Are Now Open', client: 'Yukon Gold', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Yukon Gold — Signage', client: 'Yukon Gold', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Something Dimensional Is Cooking', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Artificial Intelligence', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Meet Your Virtual Business Representative', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'AI-Powered Chatbots', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'A Chatbot Built Around Your Goals', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Ready to Transform Your Customer Experience?', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Meet Your Virtual Business Representative — Story', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'SEO — Found First on Google (Story)', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'SEO — Found First on Google', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'We Are Hiring Interns', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'We Are Hiring Interns — Roles', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Join Our Teaching Team (Story)', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Partner With Automation', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Running a Clinic or Hospital?', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Join Our Teaching Team', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Check Out Our Portfolio', client: 'Qmark Technolabs', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Eid Mubarak', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Join Our Sales Team', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Dive Into Elegance — Jan 9–11', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Fashion Expo Invitation — Stall 43', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: 'New Year, New Me', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: 'New Year, New Me — Expo Announcement', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: '3 Days to Go', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: '2 Days to Go', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: '1 Day to Go', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Price Starts From ₹499', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Scan to Connect', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Thank You for Visiting', client: 'PlanD', year: '', category: 'Brand & Agency', src: '' },
  { title: 'A New Visual Revolution', client: 'Vizapps', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Changing the Way We See Things', client: 'Vizapps', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Create Your Virtual Space in 5 Minutes', client: 'Vizapps', year: '', category: 'Brand & Agency', src: '' },
  { title: 'What If We Had More Options?', client: 'Vizapps', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Turn Your Story Into a Game', client: 'Vizapps', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Why Scroll When You Can Explore in 3D', client: 'Vizapps', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Explore Together in 3D Space', client: 'Vizapps', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Vizapps.io', client: 'Vizapps', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Products They Can Experience Virtually', client: 'Vizapps', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Interact, Express and Explore', client: 'Vizapps', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Make Managing Customers Easier', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Struggling to Manage Multiple Businesses?', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'What If Selling Online Cost Less?', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Platform Fees Are Killing Your Profits', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Ever Wonder Why Selling Online Costs So Much?', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Made Simple, Made Powerful', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Make Managing Business Easier', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Launch Your Storefront in a Few Clicks', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Why Complicate It?', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Your Business, Your Rules', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Selling Online Shouldn\'t Be This Hard', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'The Business Backend You Always Wanted', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Wanna Build an E-commerce?', client: 'Bizzscribe', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Smarter, Faster Shipping and Fulfilment', client: 'Azo Logistics', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Simplify Your Logistics & Fulfilment', client: 'Azo Logistics', year: '', category: 'Brand & Agency', src: '' },
  { title: '27,000+ Pincodes Across India', client: 'Azo Logistics', year: '', category: 'Brand & Agency', src: '' },
  { title: 'We Pick, Pack, Deliver — You Track', client: 'Azo Logistics', year: '', category: 'Brand & Agency', src: '' },
  { title: '20,000+ Bookings Completed', client: 'Azo Logistics', year: '', category: 'Brand & Agency', src: '' },
  { title: 'We\'re Hiring — Sales & Marketing Executive', client: 'Azo Logistics', year: '', category: 'Brand & Agency', src: '' },
  { title: 'A Catalyst for Change in E-waste', client: 'Ewaco', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Anything and Everything', client: 'Ewaco', year: '', category: 'Brand & Agency', src: '' },
  { title: '52 Million Tonnes of E-waste a Year', client: 'Ewaco', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Planet, People, Ethics', client: 'Ewaco', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Pledged to SDG-12 and Qatar Clean', client: 'Ewaco', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Trash Is Not the Right Place', client: 'Ewaco', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Discover Our Products', client: 'Ewaco', year: '', category: 'Brand & Agency', src: '' },
  { title: 'A More Sustainable World', client: 'Ewaco', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Commitment to the Environment', client: 'Ewaco', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Happy Onam', client: 'JC Academy', year: '', category: 'Brand & Agency', src: '' },
  { title: '+1 Science & Commerce Admission Continues', client: 'JC Academy', year: '', category: 'Brand & Agency', src: '' },
  { title: '+1 Admission Continues — Graduate', client: 'JC Academy', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Admission Started (Story)', client: 'JC Academy', year: '', category: 'Brand & Agency', src: '' },
  { title: 'Sleep Is Your Superpower', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Why Reading Matters', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Inizio — The Beginning', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Sufi Music Saga — Sameer Binzi & Imam Majboor', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Speaker Note — Nikhil Kilivayil', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Chief Guest — Nikhil Kilivayil', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Sufi Music Saga — Speaker Note', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Lumière', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Chief Guest — Dr Ameer Hassan', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Lumière — What the Name Means', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Avenir — Passes Out Now', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'VIP Pass', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Regular Pass', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Literati Assemble', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Which Is Your Favourite TED Talk?', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Six Powerful Quotes from Indian TED Speakers', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Kiran Bedi — Life Is on an Incline', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Simon Sinek — People Don\'t Buy What You Do', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Ken Robinson — A Revolution in Education', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Advice for Self-Doubt (Story)', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Titus Kaphar — Voices Unheard', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Want to Join TEDxFarookCollege? (Story)', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'TED Circles', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'TED Circles — Confidence', client: 'TEDxFarookCollege', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'TED Circles — Desires of Future Self', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'X — Coming Soon', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Community — Launching', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'Keep Your Eyes Open — Season 2', client: 'TEDxFarookCollege', year: '2023', category: 'Campus & Community', src: '' },
  { title: '50% of Tickets Sold Out', client: 'TEDxFarookCollege', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'Lumière — Volunteer Call', client: 'TEDxFarookCollege', year: '', category: 'Campus & Community', src: '' },
  { title: 'The FedTalk Frenzy', client: 'fedtalk, Farook College', year: '2023', category: 'Campus & Community', src: '/images/posters/fedtalk-frenzy.webp' },
  { title: 'Spot the Ball & Quiz Challenge', client: 'Association of Computer Science, Farook College', year: '2022', category: 'Campus & Community', src: '' },
  { title: 'Capacity Enhancement Programme', client: 'Dept. of Computer Science, Farook College', year: '', category: 'Campus & Community', src: '' },
  { title: 'Skill Development Programme', client: 'Dept. of Computer Science, Farook College', year: '', category: 'Campus & Community', src: '' },
  { title: 'Dhavoud Memorial Excellence Award', client: 'Farook College', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'Da\'wa Fund Collection', client: 'MSM Farook College', year: '2024', category: 'Campus & Community', src: '' },
  { title: 'Secured Admission — Digital University of Kerala', client: 'Association of Computer Science, Farook College', year: '', category: 'Campus & Community', src: '' },
  { title: 'Eureka Hour — Episode 1', client: 'Startup Cell, Farook College', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'Eureka Hour — Episode 2', client: 'Startup Cell, Farook College', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'FACCOMS \'23', client: 'Farook College', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'FedTalk — Fathima Dhilfa', client: 'fedtalk, Farook College', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'FedTalk — Juman Jafar', client: 'fedtalk, Farook College', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'FedTalk — Aman Rehman', client: 'fedtalk, Farook College', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'Office Bearers', client: 'Farook College', year: '', category: 'Campus & Community', src: '' },
  { title: 'Join Us in Making a Difference', client: 'The Care Unity', year: '', category: 'Campus & Community', src: '' },
  { title: 'EXIT (CS23) — Farewell', client: 'Dept. of Computer Science, Farook College', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'Medical Image Processing Using AI', client: 'Dept. of Computer Science, Farook College', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'Payasam Fest', client: 'Palliative Care Unit, Farook College', year: '', category: 'Campus & Community', src: '' },
  { title: 'Beyond the Classroom — National Seminar', client: 'KPCMSF & Farook College', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'National Startup Day', client: 'Startup Cell, Farook College', year: '', category: 'Campus & Community', src: '' },
  { title: 'Interdepartment Football Tournament', client: 'Farook College', year: '2022', category: 'Campus & Community', src: '' },
  { title: 'Ragazza — Women\'s Cell Inauguration', client: 'Women\'s Cell, Farook College', year: '2022', category: 'Campus & Community', src: '' },
  { title: 'Study Jams — Coming Soon', client: 'TinkerHub Farook College', year: '', category: 'Campus & Community', src: '' },
  { title: 'Execom 2023–24', client: 'TinkerHub Farook College', year: '2023', category: 'Campus & Community', src: '' },
  { title: 'TinkHerHack 2.0 — Register Now', client: 'TinkerHub', year: '2024', category: 'Campus & Community', src: '' },
  { title: 'TinkHerHack 2.0 — Coming Soon', client: 'TinkerHub', year: '2024', category: 'Campus & Community', src: '' },
]);
